### ISSUE TITLE
Option to disable rulers globally. 

### ISSUE THREAD

**Issue by anthonydeaver** [illandril/FoundryVTT-grid-labels#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Most my games have Landing pages and, my West Marches game I'm using the hex grid, none of which use the Rulers. Would prefer they don't show up for my players on those pages. 

**Describe alternatives you've considered**
Are there any, other than making every player turn them off?

**What system(s) do you want this feature to work with?**
All?

**What other modules do you use that you want to ensure work well with this feature?**
Add the names of other modules you use here.

**Additional context**
![Screenshot 2024-05-20 185403](https://github.com/illandril/FoundryVTT-grid-labels/assets/638054/cdbd4493-6860-4cf5-bd4b-59298b026f18)

**Comment by illandril** [comment]
For the Landing pages, you can set the scene's "Grid Type" to "Gridless". Gridless scenes never show the ruler nor the grid labels.

For rulers, I should have changed the default setting to off, and I'm going to change that default... so any players who newly connect will start with rulers off.
Unfortunately, there's no way for me to know if someone's local settings are set to "Show Rulers" because they want rulers, or because they loaded the game previously with an older version of the module and didn't know they could turn it off, so I don't want to wholesale change the setting for everyone on upgrade.

For any players that have already loaded with the old default, instead of telling them how to turn it off in the settings, you can hide it for them by using a [Script Macro](https://github.com/illandril/FoundryVTT-grid-labels?tab=readme-ov-file#script-macros)...
```
illandril.gridLabels.rulers.hide(true);
```

Any players (including GMs) connected will have their setting disabled when you run this script.

Note: The settings are stored at the "client" level, so if one player uses two different devices (or two different browsers on the same device), it's possible they might have the rulers on in one but not the other.

**Comment by anthonydeaver** [comment]
off by default works for me, thanks! 🥇
